### ISSUE TITLE
Can not install the package

### ISSUE THREAD

**Issue by yejunbin** [danielriosgarza/MAMBO#2]
I git clone MAMBO and install it through " python setup_bte_functions.py install", here is the log info:

running install
running build
running build_ext
skipping 'bottom_up_ecology.c' Cython extension (up-to-date)
running install_lib
creating /home/ye/python2.7/lib/python2.7/site-packages/bottom_up_ecology
copying build/lib.linux-x86_64-2.7/bottom_up_ecology/pyx.so -> /home/yejunbin/python2.7/lib/python2.7/site-packages/bottom_up_ecology
running install_egg_info
Removing /home/ye/python2.7/lib/python2.7/site-packages/UNKNOWN-0.0.0-py2.7.egg-info
Writing /home/ye/python2.7/lib/python2.7/site-packages/UNKNOWN-0.0.0-py2.7.egg-info

import bottom_up_ecology  

ImportError: No module named bottom_up_ecology

**Comment by adamtongji** [comment]
We install all dependencies, but still meet same import error for  "bottom_up_ecology" and the "bottom_up_ecology_functions".

**Comment by danielriosgarza** [comment]
The functions were written in Cython, so they require compilation with the setup.py script. 

The way I do it is, from my working directory, I execute the terminal command:

$ python setup.py build_ext --inplace

After which I can import to a python session also in this directory. 


I am sure there are other ways to compile it (I didn't try, but you can check here: http://cython.readthedocs.io/en/latest/src/reference/compilation.html). Let me know if you still face any issues.
