### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by yejunbin** [danielriosgarza/MAMBO#4]
python setup_bte_functions.py build_ext --inplace

running build_ext
skipping 'bottom_up_ecology.c' Cython extension (up-to-date)
building 'bottom_up_ecology.pyx' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/home/yejunbin/python2.7/local/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c bottom_up_ecology.c -o build/temp.linux-x86_64-2.7/bottom_up_ecology.o
In file included from /home/yejunbin/python2.7/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1777:0,
                 from /home/yejunbin/python2.7/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/yejunbin/python2.7/local/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from bottom_up_ecology.c:566:
/home/yejunbin/python2.7/local/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
creating /home/yejunbin/software/MAMBO/bottom_up_ecology
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/bottom_up_ecology.o -o /home/yejunbin/software/MAMBO/bottom_up_ecology/pyx.so

Cannot import bottom_up_ecology

**Comment by danielriosgarza** [comment]
This issue has been found in more recent versions of cython. One hack I found to solve it is by adding the following line to the top of the bottom_up_ecology.pyx script:

STUFF = "Hi"


Right now I included this as a commented line on the script. You may download it again and uncomment the line.
