### ISSUE TITLE
How can I link the metabolic models to the SILVA ribosomal RNA database?

### ISSUE THREAD

**Issue by krcurtis** [danielriosgarza/MAMBO#7]
I'd like to link the MAMBO models to their "nearest" SILVA database entries.  I've started looking at the models using the python version of libsbml and reading the id field, using getId(). I get back values like "kb_g_2146_fbamdl2" for Prevotella_33.xml.  Ideally, I could get back SILVA accession numbers. What do you think is the best way to map back to SILVA database entries?

Thanks in advance!

**Comment by danielriosgarza** [comment]
Hi krcurtis,
You can find NCBI accession numbers on [this file](https://github.com/danielriosgarza/bacterial_passengers.py/blob/master/input_for_ipython_scripts/bac_database.tsv). From these you may retrieve their genomes and from the genomes their 16S genes that can be queried to the SILVA database.
