### ISSUE TITLE
Objective value from optimizing individual model changed

### ISSUE THREAD

**Issue by krcurtis** [danielriosgarza/MAMBO#8]
I found that the value from
  `list_of_models[i].optimize().objective_value`
sometimes changed, when re-evaluating the model after restoring the previous growth media with
  `set_growth_media(list_of_models[i], current_value)`

If I add some code to re-compute it and compare (by subtraction) with `z_on_current_media[i]` in the single_MCMC_run() method of bottom_up_ecology.pyx, sometimes I see a difference as much as 0.02. Although most of the time the difference is either zero or around 1e-15. When there is a change, it can throw off the re-computed Pearson correlation coefficient.

Have you run into this before? Could this be because the optimize() method doesn't always return the same value? I'm currently setting model.solver to "glpk", and I am considering switching to CPLEX. Also I'm using cobrapy 0.14.1.

Thanks.

**Comment by danielriosgarza** [comment]
I have not seen this issue before. Perhaps you can try Gurobi, it's free for academic users and I find more stable than glpk.

**Comment by krcurtis** [comment]
Ok, I will try a different solver or two. Thanks!

**Comment by krcurtis** [comment]
Finally got Gurobi installed, and re-tried this, and now, when re-computing the objective function, the difference is either reported as 0.0 or in very rare cases something like: 1.1e-16

**Comment by krcurtis** [comment]
Was finally able to try Gurobi, usually the difference when re-computing the objective function is  either zero or 1.1e-16, but I do see some larger differences, like -16.5 sometimes, so I'm not sure what this means.

**Comment by danielriosgarza** [comment]
I am not sure what it means either (I haven't seen this before). But it
sounds like you might be facing floating point errors. Could you try to use
something like numpy round and restrict the number of significant digits?
